/* Generates client/src/data/code_problems_catalog_data.ts — a static,
   harness-free catalog for the Code Lab list view. Run after editing any
   problem bank: `node scripts/gen-catalog.mjs`. A vitest keeps it in sync. */
import { build } from "esbuild";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = join(root, "client", "src", "data");
const work = mkdtempSync(join(tmpdir(), "gen-catalog-"));
const out = join(work, "index.mjs");
await build({
  entryPoints: [join(dataDir, "code_problems_index.ts")],
  bundle: true,
  format: "esm",
  platform: "node",
  outfile: out,
  logLevel: "silent",
});
const { loadAllProblems } = await import(out);

const pick = p => ({
  id: p.id,
  track: p.track,
  number: p.number,
  title: p.title,
  titleEn: p.titleEn,
  difficulty: p.difficulty,
  minutes: p.minutes,
  tags: p.tags,
  tagsEn: p.tagsEn,
  brief: p.brief,
  briefEn: p.briefEn,
  language: p.language,
  ...(p.warmupStage ? { warmupStage: p.warmupStage } : {}),
});

const entries = (await loadAllProblems()).map(pick);
const body = entries.map(e => "  " + JSON.stringify(e) + ",").join("\n");
const file = `/* AUTO-GENERATED by scripts/gen-catalog.mjs — DO NOT EDIT BY HAND.
   Regenerate after any problem-bank change; a vitest asserts it stays in
   sync with the full banks. This harness-free catalog powers the Code Lab
   list view so the first visit does not download every harness/solution. */
import type { CatalogEntry } from "./code_problems_catalog";

export const problemCatalog: CatalogEntry[] = [
${body}
];
`;
writeFileSync(
  join(dataDir, "code_problems_catalog_data.ts"),
  await format(file, { parser: "typescript" }),
);
rmSync(work, { recursive: true, force: true });
console.log(`wrote code_problems_catalog_data.ts (${entries.length} entries)`);
